package postgres

import (
	"context"

	sqlcdb "github.com/moon-eye/velune/services/auth-service/internal/infrastructure/postgres/sqlc/generated"
	"github.com/jackc/pgx/v5/pgxpool"
)

// Store bundles shared Postgres access for repositories. Generated by sqlc.
type Store struct {
	Pool *pgxpool.Pool
	Queries *sqlcdb.Queries
}

func NewStore(ctx context.Context, databaseURL string) (*Store, error) {
	cfg, err := pgxpool.ParseConfig(databaseURL)
	if err != nil {
		return nil, err
	}
	pool, err := pgxpool.NewWithConfig(ctx, cfg)
	if err != nil {
		return nil, err
	}
	if err := pool.Ping(ctx); err != nil {
		pool.Close()
		return nil, err
	}

	queries := sqlcdb.New(pool)
	return &Store{
		Pool:    pool,
		Queries: queries,
	}, nil
}

func (s *Store) Close() {
	if s == nil || s.Pool == nil {
		return
	}
	s.Pool.Close()
}

